/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xd_dl_job_ParkNative */

#ifndef _Included_xd_dl_job_ParkNative
#define _Included_xd_dl_job_ParkNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xd_dl_job_ParkNative
 * Method:    initialized
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_xd_dl_job_ParkNative_initialized
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    unitialized
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xd_dl_job_ParkNative_unitialized
  (JNIEnv *, jclass);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    getParkedCarInfo
 * Signature: (ILjava/lang/String;IZI)Lxd/dl/job/ParkedCarInfo;
 */
JNIEXPORT jobject JNICALL Java_xd_dl_job_ParkNative_getParkedCarInfo
  (JNIEnv *, jclass, jint, jstring, jint, jboolean, jint);

/*
 * Class:     xd_dl_job_ParkNative
 * Method:    payParkCarFee
 * Signature: (ILjava/lang/String;Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_xd_dl_job_ParkNative_payParkCarFee
  (JNIEnv *, jclass, jint, jstring, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
